functional:
  - Пользователь должен иметь возможность авторизации и аутентификации на сайте
  - Пользователь должен иметь возможность авторизации с помощью профиля GitHub
  - Не зарегистрированные пользователи должны иметь возможность тестовой игры
  - Пользователь должен иметь возможность создавать и участвовать в игре
  - Пользователь должен иметь возможность просматривать свой рейтинг и профиль
  - Пользователь должен иметь возможность просматривать профили и рейтинги других игроков
  - При создании игры пользователь должен иметь возможность в выборе типа игры
  - Должна быть возможность создавать турниры
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика (1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность в выборе и смене языка программирования в матче
  - У пользователя должна быть возможность вызвать другого игрока на матч
  - У пользователя должны быть возможно прекратить игру досрочно или её перезагрузки
  - У пользователя должны быть возможность смены темы "светлая" или "темная"
  - У пользователя должны быть возможность к смене языка "Русский(RU)" или "Aнглийский(EN)"
  - У пользователя должна быть возможность возврата на главную страницу
  - На сайте должно отображаться количество участников онлайн