functional:
  - Пользователь должен иметь возможность регистрации, авторизации и аутентификации на сайте
  - Пользователь должен иметь возможность авторизации с помощью профиля GitHub
  - Не зарегистрированные пользователи должны иметь возможность тестовой игры
  - Пользователь должен иметь возможность создавать и участвовать в игре
  - При создании игры пользователь должен иметь возможность в выборе типа игры
  - На платформе должна быть возможность создавать турниры
  - На сайте должно отображаться количество участников онлайн
  - На сайте должна быть возможность общаться с пользователями в чате
  - Во время матча на сайте должен отображаться алгоритм когда в реальном времени, как пользователя так и его соперника
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт должен совместим и развертываться, на последних версиях браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика (1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность просматривать свой рейтинг и профиль
  - Пользователь должен иметь возможность просматривать профили и рейтинги других игроков
  - Пользователь должен иметь смотреть за матчем других игроков
  - Пользователь должен иметь возможность в выборе и смене языка программирования в матче
  - Пользователь должен иметь возможность вызвать другого игрока на матч
  - Пользователь должен иметь возможно прекратить игру досрочно или её перезагрузить
  - Пользователь должен иметь возможность смены темы на "светлая" или "темная"
  - Пользователь должен иметь возможность сменить язык "Русский(RU)" или "Aнглийский(EN)"
  - Пользователь должен иметь возможность возврата на главную страницу кнопкой