functional:
  - Пользователь должен иметь возможность регистрации, авторизации и аутентификации на сайте
  - Пользователь должен иметь возможность авторизации с помощью профиля GitHub
  - Не зарегистрированные пользователи должны иметь возможность тестовой игры
  - Пользователь должен иметь возможность создавать и участвовать в игре
  - На платформе должна быть возможность участвовать и создавать турниры
  - На сайте должно отображаться количество участников онлайн
  - На сайте должна быть возможность общаться с пользователями в чате
non-functional:
  - Сайт должен обеспечивать безопасность и защиту персональных данных пользователя
  - Сайт должен быть удобным в использовании и оптимизированным для высокой скорости загрузки и отклика
  - Сайт должен корректно отображаться и функционировать на мобильных устройствах
  - Сайт должен быть совместим с последними версиями популярных браузеров
  - Сайт должен устойчиво работать при высокой нагрузке (1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность просматривать свой рейтинг и профиль
  - Пользователь должен иметь возможность просматривать профили и рейтинги других игроков
  - Пользователь должен иметь возможность смотреть за матчем других игроков
  - Пользователь должен иметь возможность в выборе и смене языка программирования в матче
  - Пользователь должен иметь возможность вызвать другого игрока на матч
  - Пользователь должен иметь возможно прекратить игру досрочно или её перезагрузить
  - Пользователь должен иметь возможность смены темы во время матча на "светлая" или "темная"
  - Пользователь должен иметь возможность сменить язык во время матча на "Русский(RU)" или "Aнглийский(EN)"
  - Пользователь должен иметь возможность возврата на главную страницу кнопкой